(async()=>{
  const config=window.INTERNSHIP_TRACKER_CONFIG;
  const cards=['authCard','verifyCard','recoveryCard','onboardingCard','workspace','setupNotice'];
  const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
  let mode='signin',pendingEmail='',recoveryMode=false,currentProfile=null,currentCatalog=[],currentResumes=[],currentFeedback=[];
  const show=id=>cards.forEach(card=>$('#'+card).classList.toggle('hidden',card!==id));
  const message=(selector,text,error=true)=>{const el=$(selector);el.textContent=text;el.style.color=error?'#a33535':'#23734d'};
  const escapeHtml=(value='')=>{const node=document.createElement('div');node.textContent=value??'';return node.innerHTML};
  const checkedValues=name=>$$(`input[name="${name}"]:checked`).map(input=>input.value);
  const terminal=status=>['Rejected','Withdrawn','Closed','Closed / No Longer Open'].includes(status);
  const isoToday=()=>new Date().toISOString().slice(0,10);
  const daysUntil=value=>value?Math.ceil((new Date(`${value}T12:00:00`)-new Date())/86400000):null;
  const tokenize=(value='')=>[...new Set(String(value).toLowerCase().replace(/[^a-z0-9+#.]+/g,' ').split(/\s+/).filter(word=>word.length>2&&!['and','the','with','for','from','that','this','your','you','will','are','our','intern','internship'].includes(word)))];
  const catalogId=item=>String(item.id||item.canonical_key||`${item.company}|${item.role}|${item.location}`);
  if(!config?.supabaseUrl||!config?.supabasePublishableKey||config.supabaseUrl.includes('YOUR_PROJECT')){show('setupNotice');return}
  const client=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey);

  async function routeSession(session){
    if(!session){show(recoveryMode?'recoveryCard':'authCard');return}
    if(recoveryMode){show('recoveryCard');$('#recoveryRequestForm').classList.add('hidden');$('#newPasswordForm').classList.remove('hidden');$('#recoveryTitle').textContent='Choose a new password';$('#recoveryIntro').textContent='Create a new password for your account.';return}
    const {data,error}=await client.from('profiles').select('*').eq('user_id',session.user.id).maybeSingle();
    if(error){show('onboardingCard');message('#onboardingMessage',error.message);return}
    if(!data?.onboarding_complete){show('onboardingCard');return}
    show('workspace');await loadWorkspace(data);
  }
  async function optionalTable(name,order='created_at'){const result=await client.from(name).select('*').order(order,{ascending:false});if(result.error&&['42P01','PGRST205','42703'].includes(result.error.code))return[];if(result.error)throw result.error;return result.data||[]}
  async function loadCatalog(){const {data,error}=await client.from('opportunities_catalog').select('*').order('created_at',{ascending:false});if(!error&&data?.length)return data.map(item=>({...item,posting_url:item.posting_url||item.source_url,source_url:item.source_url||item.posting_url,listing_status:item.listing_status||(item.is_active===false?'Closed':'Active')}));const response=await fetch('opportunities.json',{cache:'no-store'});if(!response.ok)throw new Error('Could not load the opportunity catalog.');return response.json()}
  async function loadWorkspace(profile){
    currentProfile=profile;
    try{
      const [catalog,tracked,contacts,resumes,feedback,preferences]=await Promise.all([loadCatalog(),optionalTable('applications'),optionalTable('networking_contacts'),optionalTable('resume_documents'),optionalTable('recommendation_feedback'),client.from('notification_preferences').select('*').maybeSingle()]);
      currentCatalog=catalog||[];currentResumes=resumes||[];currentFeedback=feedback||[];
      await syncClosedListings(tracked||[],currentCatalog);
      renderDiscovery(profile,currentCatalog,currentResumes,currentFeedback);renderTracker(tracked||[]);renderOverview(tracked||[],currentCatalog);renderNetworking(contacts||[]);renderResumes(currentResumes);renderNotificationSettings(preferences.data);
    }catch(error){message('#workspaceMessage',error.message||'Could not load your workspace.')}
  }
  function resumeRecommendation(item,resumes){
    if(!resumes.length)return{label:recommendResume(item.role_family||item.category,currentProfile?.majors||[]),score:null};
    const jobTokens=tokenize([item.role,item.role_family,item.industry,item.details_eligibility,...(item.tags||[])].join(' ')),category=String(item.role_family||item.category||'').toLowerCase();
    const scored=resumes.map(resume=>{const resumeTokens=new Set([...(resume.extracted_keywords||[]),...tokenize(resume.extracted_text||''),...tokenize(resume.resume_type)]),overlap=jobTokens.filter(token=>resumeTokens.has(token)).length,type=String(resume.resume_type||'').toLowerCase(),categoryBonus=category.split(/\W+/).some(word=>word.length>3&&type.includes(word))?8:0;return{resume,score:overlap+categoryBonus}}).sort((a,b)=>b.score-a.score)[0];
    return{label:`${scored.resume.resume_type} — ${scored.resume.file_name}`,score:scored.score};
  }
  function renderDiscovery(profile,catalog,resumes,feedback){
    const interests=[...(profile.role_interests||[]),...(profile.industries||[]),...(profile.custom_interests||[]),...(profile.majors||[]),...(profile.minors||[])].map(v=>v.toLowerCase()),locations=(profile.preferred_locations||[]).map(v=>v.toLowerCase()),feedbackMap=new Map(feedback.map(row=>[String(row.catalog_id),row]));
    const ranked=catalog.map(item=>{const haystack=[item.role,item.role_family,item.industry,item.details_eligibility,...(item.tags||[])].join(' ').toLowerCase(),interestMatches=interests.filter(value=>haystack.includes(value)||value.split(' ').some(word=>word.length>4&&haystack.includes(word))).length,location=String(item.location||`${item.city||''}, ${item.state||''}`).toLowerCase(),locationMatch=locations.some(value=>location.includes(value)||value.includes(location))?2:0,typeMatch=(profile.job_types||[]).includes(item.opportunity_type||'Internship')?2:0,modeMatch=(profile.work_modes||[]).includes(item.work_mode)?1:0,prior=feedbackMap.get(catalogId(item)),feedbackAdjustment=prior?.sentiment==='up'?3:prior?.sentiment==='down'?-8:0,match_score=interestMatches*3+locationMatch+typeMatch+modeMatch+feedbackAdjustment;return{...item,location:item.location||[item.city,item.state].filter(Boolean).join(', '),match_score,recommended:resumeRecommendation(item,resumes),feedback:prior}}).filter(item=>item.is_active!==false&&item.listing_status!=='Closed'&&item.match_score>0).sort((a,b)=>b.match_score-a.match_score);
    $('#feedSummary').textContent=`Showing ${ranked.length} matches based on your education, role, industry, location, résumé, and feedback preferences.`;
    $('#privateList').innerHTML=ranked.map(item=>`<article class="opportunity-record"><div class="record-head"><div><strong>${escapeHtml(item.company)}</strong><span>${escapeHtml(item.role)} · ${escapeHtml(item.location)}</span></div><span class="match-score">${item.match_score} match points</span></div><div class="record-tags"><span>${escapeHtml(item.opportunity_type||'Internship')}</span><span>${escapeHtml(item.work_mode||'Not listed')}</span><span>${escapeHtml(item.industry||item.role_family||'')}</span><span>${escapeHtml(item.posting_verification||item.listing_status||'Active')}</span></div><p>${escapeHtml(item.details_eligibility||'Details will be added after verification.')}</p><p><strong>Recommended résumé:</strong> ${escapeHtml(item.recommended.label)}${item.recommended.score!==null?` <small>(${item.recommended.score} matching signals)</small>`:''}</p><div class="feedback-row"><button class="feedback-button ${item.feedback?.sentiment==='up'?'selected':''}" data-feedback="up" data-id="${escapeHtml(catalogId(item))}" type="button">👍</button><button class="feedback-button ${item.feedback?.sentiment==='down'?'selected':''}" data-feedback="down" data-id="${escapeHtml(catalogId(item))}" type="button">👎</button><span>${escapeHtml(item.feedback?.reason||'Rate this recommendation')}</span></div><div class="record-actions">${item.is_demo?'<span class="demo-badge">Demo match</span>':`<a class="primary opportunity-link" href="${escapeHtml(item.posting_url||item.source_url)}" target="_blank" rel="noopener noreferrer">View posting</a>`}<button class="secondary save-match" data-id="${escapeHtml(catalogId(item))}" type="button">Save to tracker</button></div></article>`).join('')||'<p>No close matches are available yet. Edit your preferences to broaden the feed.</p>';
    $$('.save-match').forEach(button=>button.addEventListener('click',()=>saveMatch(button.dataset.id,ranked)));$$('.feedback-button').forEach(button=>button.addEventListener('click',()=>saveFeedback(button.dataset.id,button.dataset.feedback)));
  }
  async function saveFeedback(id,sentiment){const item=currentCatalog.find(row=>catalogId(row)===id);if(!item)return;const reason=sentiment==='down'?(prompt('Optional: why is this not a good match?','Wrong role, location, timing, or qualifications')||'').trim():'',{data:{user}}=await client.auth.getUser(),uuid=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(String(item.id))?item.id:null;if(!uuid){message('#workspaceMessage','Feedback will become persistent after this posting is synced to the live catalog.');return}const {error}=await client.from('recommendation_feedback').upsert({user_id:user.id,catalog_id:uuid,sentiment,reason},{onConflict:'user_id,catalog_id'});if(error){message('#workspaceMessage',error.message);return}message('#workspaceMessage','Recommendation feedback saved.',false);await loadWorkspace(currentProfile)}
  async function saveMatch(id,ranked){const item=ranked.find(row=>catalogId(row)===id),{data:{user}}=await client.auth.getUser();if(!item||!user)return;const uuid=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(String(item.id))?item.id:null,recommendation=resumeRecommendation(item,currentResumes),payload={user_id:user.id,catalog_id:uuid,company:item.company,role:item.role,location:item.location,career_area:item.role_family||item.category,posting_url:item.posting_url||item.source_url,source:item.source||'Recommendation feed',status:'Planning',recommended_resume:recommendation.label,deadline:item.deadline,priority_score:Math.min(100,60+item.match_score*4),term:item.term,city:item.city,state:item.state,work_mode:item.work_mode,listing_status:item.listing_status||'Active',details_eligibility:item.details_eligibility,source_url:item.source_url||item.posting_url,priority_level:item.match_score>=7?'High':item.match_score>=4?'Medium':'Low',link_type:item.link_type||'Needs review',posting_verification:item.posting_verification||'Not Verified',last_verified:item.last_verified,company_interest:3,role_fit:4,resume_match:recommendation.score===null?3:Math.max(1,Math.min(5,Math.ceil(recommendation.score/4))),application_guardrail:'No conflict'};const {error}=await client.from('applications').insert(payload);if(error){message('#workspaceMessage',error.code==='23505'?'This position is already saved.':error.message);return}message('#workspaceMessage','Saved to your tracker.',false);await loadWorkspace(currentProfile)}
  function recommendResume(roleFamily,majors){const text=[roleFamily,...majors].join(' ').toLowerCase();if(text.includes('finance')||text.includes('account'))return'Finance résumé';if(text.includes('marketing')||text.includes('sales')||text.includes('communication'))return'Sales / Marketing résumé';if(text.includes('consult')||text.includes('strategy'))return'Consulting résumé';if(text.includes('data')||text.includes('analytics')||text.includes('information'))return'Data Analytics résumé';if(text.includes('operation')||text.includes('supply'))return'Operations résumé';return'General résumé'}

  function renderOverview(records,catalog){const active=records.filter(r=>!terminal(r.status)),archived=records.length-active.length,metrics=[['Active opportunities',active.length],['High priority',active.filter(r=>r.priority_level==='High').length],['Awaiting response',active.filter(r=>r.status==='Applied').length],['Interviews',active.filter(r=>r.status==='Interviewing').length],['Offers',active.filter(r=>r.status==='Offer').length],['Archived',archived]];$('#webMetrics').innerHTML=metrics.map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join('');const weekAgo=Date.now()-7*86400000,newJobs=catalog.filter(item=>new Date(item.created_at||item.first_seen_at||0).getTime()>=weekAgo).length,deadlines=active.filter(r=>{const days=daysUntil(r.deadline);return days!==null&&days>=0&&days<=14}).length,awaiting=active.filter(r=>r.status==='Applied').length,priority=[...active].sort((a,b)=>(b.priority_score||0)-(a.priority_score||0))[0]?.company||'None yet';$('#weeklySummary').innerHTML=[['New catalog opportunities',newJobs],['Deadlines in 14 days',deadlines],['Applications awaiting responses',awaiting],['Suggested priority',priority]].map(([label,value])=>`<article><span>${label}</span><strong>${escapeHtml(String(value))}</strong></article>`).join('');$('#nextActions').innerHTML=[...active].sort((a,b)=>(b.priority_score||0)-(a.priority_score||0)).slice(0,4).map(record=>`<div class="compact-action"><strong>${escapeHtml(record.company)} — ${escapeHtml(record.role)}</strong><span>${escapeHtml(record.priority_level||'Unscored')} priority · ${escapeHtml(record.status)}</span></div>`).join('')||'<p>Save opportunities from Discover to build your action list.</p>';renderNotifications(active)}
  function renderNotifications(records){const items=[];records.forEach(record=>{const deadline=daysUntil(record.deadline);if(deadline!==null&&deadline>=0&&deadline<=7)items.push(`${record.company}: deadline in ${deadline} day${deadline===1?'':'s'}.`);const follow=daysUntil(record.follow_up_date);if(follow!==null&&follow<=0)items.push(`${record.company}: follow-up is due.`)});$('#notificationList').innerHTML=items.map(item=>`<div class="compact-action"><strong>${escapeHtml(item)}</strong></div>`).join('')||'<p>No immediate reminders.</p>';if('Notification'in window&&Notification.permission==='granted'&&items.length&&!sessionStorage.getItem('tracker-notified')){new Notification('Internship Tracker',{body:items[0]});sessionStorage.setItem('tracker-notified','1')}}
  function renderTracker(records){const active=records.filter(record=>!terminal(record.status)),archived=records.filter(record=>terminal(record.status));$('#trackerList').innerHTML=active.map(recordCard).join('')||'<p>No saved opportunities yet.</p>';$('#archiveList').innerHTML=archived.map(recordCard).join('')||'<p>No archived opportunities.</p>';$$('.record-status').forEach(select=>select.addEventListener('change',()=>updateStatus(select.dataset.id,select.value)));$$('.save-record').forEach(button=>button.addEventListener('click',()=>saveRecord(button.dataset.id)))}
  function recordCard(r){const statuses=['Planning','Applied','Interviewing','Offer','Rejected','Withdrawn','Closed / No Longer Open'];return `<details class="tracked-record"><summary><span><strong>${escapeHtml(r.company)}</strong><small>${escapeHtml(r.role)} · ${escapeHtml(r.location||'Location not listed')}</small></span><span class="priority-pill">${escapeHtml(r.priority_level||'Unscored')} · ${escapeHtml(r.status)}</span></summary><div class="record-grid"><label>Application status<select class="record-status" data-id="${r.id}">${statuses.map(status=>`<option ${status===r.status?'selected':''}>${status}</option>`).join('')}</select></label><div><b>Category</b>${escapeHtml(r.career_area||'')}</div><div><b>Term</b>${escapeHtml(r.term||'')}</div><div><b>Work mode</b>${escapeHtml(r.work_mode||'')}</div><div><b>Listing status</b>${escapeHtml(r.listing_status||'')}</div><label>Deadline<input class="edit-deadline" data-id="${r.id}" type="date" value="${escapeHtml(r.deadline||'')}"></label><div><b>Priority score</b>${escapeHtml(String(r.priority_score??''))}</div><div><b>Recommended résumé</b>${escapeHtml(r.recommended_resume||'Review manually')}</div><div><b>Posting verification</b>${escapeHtml(r.posting_verification||'Not verified')}</div><label>Follow-up date<input class="edit-followup" data-id="${r.id}" type="date" value="${escapeHtml(r.follow_up_date||'')}"></label><label>Company interest (1–5)<input class="edit-interest" data-id="${r.id}" type="number" min="1" max="5" value="${r.company_interest||3}"></label><label>Role fit (1–5)<input class="edit-fit" data-id="${r.id}" type="number" min="1" max="5" value="${r.role_fit||3}"></label><label class="wide">Notes<textarea class="edit-notes" data-id="${r.id}">${escapeHtml(r.user_notes||r.follow_up_notes||r.notes||'')}</textarea></label><div class="wide"><b>Eligibility and details</b>${escapeHtml(r.details_eligibility||'')}</div></div><div class="record-actions"><button class="secondary save-record" data-id="${r.id}" type="button">Save edits</button>${r.source_url?`<a class="primary opportunity-link" href="${escapeHtml(r.source_url)}" target="_blank" rel="noopener noreferrer">Apply on source site</a>`:''}</div></details>`}
  async function saveRecord(id){const value=selector=>$(selector+`[data-id="${id}"]`)?.value||null,changes={deadline:value('.edit-deadline'),follow_up_date:value('.edit-followup'),company_interest:Number(value('.edit-interest'))||3,role_fit:Number(value('.edit-fit'))||3,user_notes:value('.edit-notes')};const {error}=await client.from('applications').update(changes).eq('id',id);if(error){message('#workspaceMessage',error.message);return}message('#workspaceMessage','Tracker edits saved.',false);await loadWorkspace(currentProfile)}
  async function updateStatus(id,status){const isTerminal=terminal(status),changes={status,archived_on:isTerminal?isoToday():null,archive_reason:isTerminal?status:null,date_applied:status==='Applied'?isoToday():undefined};Object.keys(changes).forEach(key=>changes[key]===undefined&&delete changes[key]);const {error}=await client.from('applications').update(changes).eq('id',id);if(error){message('#workspaceMessage',error.message);return}message('#workspaceMessage',isTerminal?'Moved to Archive.':'Application status updated.',false);await loadWorkspace(currentProfile)}
  async function syncClosedListings(records,catalog){const closedIds=new Set(catalog.filter(item=>item.is_active===false||String(item.listing_status).toLowerCase()==='closed').map(item=>String(item.id))),updates=records.filter(record=>record.catalog_id&&closedIds.has(String(record.catalog_id))&&record.listing_status!=='Closed');await Promise.all(updates.map(record=>client.from('applications').update({listing_status:'Closed',posting_verification:'Closed — catalog verification'}).eq('id',record.id)))}
  function renderNetworking(contacts){$('#networkingList').innerHTML=contacts.map(contact=>`<article class="opportunity-record"><strong>${escapeHtml(contact.contact_name)} · ${escapeHtml(contact.company)}</strong><p>${escapeHtml(contact.current_title||'Title not entered')} · ${escapeHtml(contact.location||'Location not entered')}</p><div class="record-tags"><span>${escapeHtml(contact.verification_status)}</span><span>${escapeHtml(contact.outreach_status)}</span><span>${escapeHtml(contact.connection_type||'Contact')}</span></div>${contact.verification_source?`<a href="${escapeHtml(contact.verification_source)}" target="_blank" rel="noopener noreferrer">Open verification source</a>`:''}</article>`).join('')||'<p>No verified contacts added.</p>'}
  function renderResumes(resumes){$('#resumeList').innerHTML=resumes.map(resume=>`<article class="opportunity-record"><div class="record-head"><div><strong>${escapeHtml(resume.resume_type)} résumé</strong><span>${escapeHtml(resume.file_name)} · uploaded ${escapeHtml(String(resume.created_at).slice(0,10))}</span></div><button class="text-button delete-resume" data-id="${resume.id}" data-path="${escapeHtml(resume.storage_path)}" type="button">Delete</button></div><div class="record-tags"><span>${escapeHtml(resume.analysis_status||'Pending')}</span><span>${(resume.extracted_keywords||[]).length} keywords</span></div><p>${escapeHtml(resume.analysis_summary||'Upload analysis has not run yet.')}</p></article>`).join('')||'<p>No résumé versions uploaded.</p>';$$('.delete-resume').forEach(button=>button.addEventListener('click',()=>deleteResume(button.dataset.id,button.dataset.path)))}
  async function extractPdf(file){try{const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let page=1;page<=Math.min(pdf.numPages,5);page++){const content=await(await pdf.getPage(page)).getTextContent();text+=content.items.map(item=>item.str).join(' ')+'\n'}const keywords=tokenize(text).slice(0,120);return{text:text.slice(0,50000),keywords,status:'Analyzed',summary:`Extracted ${keywords.length} résumé keywords from ${pdf.numPages} page${pdf.numPages===1?'':'s'}.`}}catch(error){return{text:'',keywords:[],status:'Needs review',summary:`Text extraction could not complete: ${error.message}`}}}
  async function deleteResume(id,path){if(!confirm('Delete this résumé file and its analysis?'))return;const {error:storageError}=await client.storage.from('resumes').remove([path]);if(storageError){message('#workspaceMessage',storageError.message);return}const {error}=await client.from('resume_documents').delete().eq('id',id);if(error){message('#workspaceMessage',error.message);return}message('#workspaceMessage','Résumé deleted.',false);await loadWorkspace(currentProfile)}
  function renderNotificationSettings(settings){const form=$('#notificationForm');if(!form)return;form.in_app_enabled.checked=settings?.in_app_enabled??true;form.browser_enabled.checked=settings?.browser_enabled??false;form.weekly_email_enabled.checked=settings?.weekly_email_enabled??false;form.deadline_days.value=settings?.deadline_days??7;form.follow_up_days.value=settings?.follow_up_days??7}

  $$('.auth-tab').forEach(tab=>tab.addEventListener('click',()=>{mode=tab.dataset.mode;$$('.auth-tab').forEach(item=>item.classList.toggle('active',item===tab));$$('.signup-only').forEach(el=>el.classList.toggle('hidden',mode!=='signup'));$$('.signin-only').forEach(el=>el.classList.toggle('hidden',mode!=='signin'));$('#confirmPassword').required=mode==='signup';$('#password').autocomplete=mode==='signin'?'current-password':'new-password';$('#authForm button[type="submit"]').textContent=mode==='signin'?'Sign in':'Create account';$('#authMessage').textContent=''}));
  $('#authForm').addEventListener('submit',async event=>{event.preventDefault();message('#authMessage','Working…',false);const email=$('#email').value.trim(),password=$('#password').value;if(mode==='signup'){if(password!==$('#confirmPassword').value){message('#authMessage','Passwords do not match.');return}const {error}=await client.auth.signUp({email,password,options:{emailRedirectTo:new URL('account.html',location.href).href}});if(error){message('#authMessage',error.message);return}pendingEmail=email;$('#verifyEmail').textContent=email;$('#verificationCode').value='';show('verifyCard');return}const {data,error}=await client.auth.signInWithPassword({email,password});if(error){message('#authMessage',error.message);return}await routeSession(data.session)});
  $('#verifyForm').addEventListener('submit',async event=>{event.preventDefault();message('#verifyMessage','Verifying…',false);const {data,error}=await client.auth.verifyOtp({email:pendingEmail,token:$('#verificationCode').value.trim(),type:'email'});if(error){message('#verifyMessage',error.message);return}message('#verifyMessage','Email verified.',false);await routeSession(data.session)});$('#backToSignIn').addEventListener('click',()=>show('authCard'));
  $('#forgotPassword').addEventListener('click',()=>{recoveryMode=false;$('#recoveryRequestForm').classList.remove('hidden');$('#newPasswordForm').classList.add('hidden');$('#recoveryTitle').textContent='Reset your password';$('#recoveryIntro').textContent='Enter your email and we’ll send a secure reset link.';show('recoveryCard')});$('#recoveryBack').addEventListener('click',()=>{recoveryMode=false;show('authCard')});
  $('#recoveryRequestForm').addEventListener('submit',async event=>{event.preventDefault();const redirectTo=new URL('account.html?recovery=1',location.href).href,{error}=await client.auth.resetPasswordForEmail($('#recoveryEmail').value.trim(),{redirectTo});message('#recoveryMessage',error?error.message:'If an account exists for that email, a reset message has been sent.',Boolean(error))});
  $('#newPasswordForm').addEventListener('submit',async event=>{event.preventDefault();const password=$('#newPassword').value;if(password!==$('#confirmNewPassword').value){message('#recoveryMessage','Passwords do not match.');return}const {error}=await client.auth.updateUser({password});if(error){message('#recoveryMessage',error.message);return}recoveryMode=false;await client.auth.signOut();show('authCard');message('#authMessage','Password updated. Sign in with your new password.',false)});
  $('#onboardingForm').addEventListener('submit',async event=>{event.preventDefault();const roleInterests=checkedValues('role_interests'),industries=checkedValues('industries'),jobTypes=checkedValues('job_types');if(!roleInterests.length||!industries.length||!jobTypes.length){message('#onboardingMessage','Select at least one field, role type, and opportunity type.');return}const form=new FormData(event.currentTarget),{data:{user}}=await client.auth.getUser(),csv=name=>String(form.get(name)||'').split(',').map(v=>v.trim()).filter(Boolean),profile={user_id:user.id,in_school:form.get('in_school')==='true',education_level:form.get('education_level')||null,school_name:form.get('school_name')||null,graduation_year:Number(form.get('graduation_year'))||null,majors:csv('majors'),minors:csv('minors'),career_areas:roleInterests,industries,role_interests:roleInterests,custom_interests:csv('custom_interests'),job_types:jobTypes,work_modes:checkedValues('work_modes'),preferred_locations:csv('preferred_locations'),onboarding_complete:true};const {error}=await client.from('profiles').upsert(profile,{onConflict:'user_id'});if(error){message('#onboardingMessage',error.message);return}show('workspace');await loadWorkspace(profile)});
  $('#studentStatus').addEventListener('change',event=>{$('#studentFields').classList.toggle('hidden',event.target.value!=='true')});$('#editPreferences').addEventListener('click',()=>show('onboardingCard'));
  $('#networkingForm').addEventListener('submit',async event=>{event.preventDefault();const {data:{user}}=await client.auth.getUser(),payload={...Object.fromEntries(new FormData(event.currentTarget)),user_id:user.id,verified_on:event.currentTarget.verification_status.value==='Verified'?isoToday():null},{error}=await client.from('networking_contacts').insert(payload);if(error){message('#workspaceMessage',error.message);return}event.currentTarget.reset();message('#workspaceMessage','Contact added.',false);await loadWorkspace(currentProfile)});
  $('#resumeForm').addEventListener('submit',async event=>{event.preventDefault();const file=event.currentTarget.resume_file.files[0],type=event.currentTarget.resume_type.value,{data:{user}}=await client.auth.getUser();if(!file||!user)return;message('#workspaceMessage','Analyzing and uploading résumé…',false);const analysis=await extractPdf(file),safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${user.id}/${Date.now()}_${safeName}`,{error:uploadError}=await client.storage.from('resumes').upload(path,file,{contentType:'application/pdf',upsert:false});if(uploadError){message('#workspaceMessage',uploadError.message);return}const {error}=await client.from('resume_documents').insert({user_id:user.id,resume_type:type,file_name:file.name,storage_path:path,extracted_text:analysis.text,extracted_keywords:analysis.keywords,analysis_status:analysis.status,analysis_summary:analysis.summary});if(error){await client.storage.from('resumes').remove([path]);message('#workspaceMessage',error.message);return}event.currentTarget.reset();message('#workspaceMessage','Résumé uploaded privately and analyzed.',false);await loadWorkspace(currentProfile)});
  $('#notificationForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget),{data:{user}}=await client.auth.getUser();if(event.currentTarget.browser_enabled.checked&&'Notification'in window&&Notification.permission!=='granted'){const permission=await Notification.requestPermission();if(permission!=='granted')event.currentTarget.browser_enabled.checked=false}const payload={user_id:user.id,in_app_enabled:event.currentTarget.in_app_enabled.checked,browser_enabled:event.currentTarget.browser_enabled.checked,weekly_email_enabled:event.currentTarget.weekly_email_enabled.checked,deadline_days:Number(form.get('deadline_days')),follow_up_days:Number(form.get('follow_up_days'))},{error}=await client.from('notification_preferences').upsert(payload,{onConflict:'user_id'});message('#workspaceMessage',error?error.message:'Notification settings saved.',Boolean(error))});
  $('#deleteAccount').addEventListener('click',async()=>{if(prompt('Type DELETE to permanently remove your account and all private data.')!=='DELETE')return;const {error}=await client.functions.invoke('delete-account',{body:{confirm:true}});if(error){message('#workspaceMessage',`${error.message}. The secure deletion function must be deployed before this control can be used.`);return}await client.auth.signOut();show('authCard');message('#authMessage','Your account and private data were deleted.',false)});
  $$('.workspace-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.workspace-tab').forEach(item=>item.classList.toggle('active',item===tab));$$('.workspace-panel').forEach(panel=>panel.classList.toggle('active',panel.id===tab.dataset.panel+'Panel'));$('#workspaceTitle').textContent={overview:'Dashboard',discover:'Recommended opportunities',tracker:'My tracker',archive:'Archive',resumes:'Résumés',networking:'Networking',settings:'Settings'}[tab.dataset.panel]}));
  $$('.sign-out').forEach(button=>button.addEventListener('click',async()=>{await client.auth.signOut();show('authCard')}));client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')recoveryMode=true;setTimeout(()=>routeSession(session),0)});recoveryMode=new URLSearchParams(location.search).get('recovery')==='1';const {data:{session}}=await client.auth.getSession();await routeSession(session);
})();
