'use strict';
const $=selector=>document.querySelector(selector);const state={records:[],filtered:[],selected:null};const fields={query:$('#query'),field:$('#field'),mode:$('#mode'),status:$('#status'),sort:$('#sort')};
function el(tag,options={},children=[]){const node=document.createElement(tag);for(const[key,value]of Object.entries(options)){if(key==='className')node.className=value;else if(key==='text')node.textContent=value;else if(key==='dataset')Object.assign(node.dataset,value);else node.setAttribute(key,value)}for(const child of children)node.append(child);return node}
function safeHttps(value){try{const url=new URL(value);return url.protocol==='https:'?url.href:null}catch{return null}}
function dateLabel(value){if(!value)return'Not listed';const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.getTime())?'Not listed':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function ageInDays(value){if(!value)return Infinity;return Math.floor((Date.now()-new Date(`${value}T12:00:00`).getTime())/86400000)}
function effectiveStatus(record){const current=record.listing_status||'Needs review';return current==='Active'&&ageInDays(record.last_verified)>14?'Needs re-verification':current}
function statusClass(record){const status=effectiveStatus(record).toLowerCase();if(status==='active')return'active';if(status==='closed'||status==='expired')return'closed';return'review'}
function addOptions(select,values){values.filter(Boolean).sort((a,b)=>a.localeCompare(b)).forEach(value=>select.append(el('option',{value,text:value})))}
function searchText(record){return[record.company,record.role,record.location,record.field_key,record.role_key,record.industry,...(record.tags||[])].join(' ').toLowerCase()}
function renderCard(record){const button=el('button',{className:`opportunity-card ${state.selected===record.id?'selected':''}`,type:'button',dataset:{id:String(record.id)}});button.append(el('span',{className:'card-top'},[el('span',{className:'company-mark',text:(record.company||'?').slice(0,1).toUpperCase()}),el('span',{},[el('strong',{text:record.role||'Untitled opportunity'}),el('small',{text:record.company||'Unknown company'})])]),el('span',{className:'location',text:record.location||[record.city,record.state].filter(Boolean).join(', ')||'Location not listed'}),el('span',{className:'card-tags'},[el('span',{text:record.opportunity_type||'Opportunity'}),el('span',{text:record.work_mode||'Mode not listed'}),el('span',{className:`status ${statusClass(record)}`,text:effectiveStatus(record)})]),el('span',{className:'verified',text:`Last verified ${dateLabel(record.last_verified)}`}));button.addEventListener('click',()=>{state.selected=record.id;renderResults();renderDetail(record)});return button}
function fact(label,value){return el('div',{},[el('dt',{text:label}),el('dd',{text:value||'Not listed'})])}
function renderDetail(record){const panel=$('#detail');panel.replaceChildren();const url=safeHttps(record.posting_url||record.source_url);panel.append(el('div',{className:'detail-head'},[el('div',{},[el('p',{className:'eyebrow',text:effectiveStatus(record).toUpperCase()}),el('h2',{text:record.role||'Untitled opportunity'}),el('p',{text:`${record.company||'Unknown company'} · ${record.location||'Location not listed'}`})]),el('span',{className:`status ${statusClass(record)}`,text:effectiveStatus(record)})]),el('dl',{className:'facts'},[fact('Field',record.field_key),fact('Role family',record.role_key||record.role_family),fact('Opportunity type',record.opportunity_type),fact('Work mode',record.work_mode),fact('Term',record.term),fact('Deadline',dateLabel(record.deadline)),fact('Last verified',dateLabel(record.last_verified)),fact('Source type',record.link_type||record.source)]));if(record.description||record.details_eligibility)panel.append(el('h3',{text:'Details'}),el('p',{text:record.description||record.details_eligibility}));if(record.education_requirements)panel.append(el('h3',{text:'Education requirements'}),el('p',{text:record.education_requirements}));panel.append(url?el('a',{className:'primary-link',href:url,target:'_blank',rel:'noopener noreferrer',text:'Open source posting'}):el('p',{className:'warning',text:'No safe HTTPS source is available for this record.'}))}
function renderResults(){const results=$('#results');results.replaceChildren(...state.filtered.map(renderCard));if(!state.filtered.length)results.append(el('div',{className:'empty',text:'No opportunities match these filters.'}));$('#resultSummary').textContent=`${state.filtered.length} of ${state.records.length} public opportunities`}
function applyFilters(){const query=fields.query.value.trim().toLowerCase();state.filtered=state.records.filter(record=>(!query||searchText(record).includes(query))&&(!fields.field.value||record.field_key===fields.field.value)&&(!fields.mode.value||record.work_mode===fields.mode.value)&&(!fields.status.value||effectiveStatus(record)===fields.status.value));const sort=fields.sort.value;state.filtered.sort((a,b)=>sort==='company'?String(a.company).localeCompare(String(b.company)):sort==='deadline'?String(a.deadline||'9999').localeCompare(String(b.deadline||'9999')):String(b.last_verified||'').localeCompare(String(a.last_verified||'')));if(!state.filtered.some(record=>record.id===state.selected))state.selected=state.filtered[0]?.id??null;renderResults();const selected=state.filtered.find(record=>record.id===state.selected);if(selected)renderDetail(selected);else $('#detail').replaceChildren(el('p',{className:'empty',text:'No opportunity matches these filters.'}))}
async function loadCatalog(){try{const response=await fetch('opportunities.json',{cache:'no-store'});if(!response.ok)throw new Error(`Catalog request failed (${response.status})`);const records=await response.json();if(!Array.isArray(records))throw new Error('Catalog format is invalid');state.records=records.map((record,index)=>({...record,id:record.id??record.canonical_key??index}));addOptions(fields.field,[...new Set(state.records.map(record=>record.field_key))]);addOptions(fields.mode,[...new Set(state.records.map(record=>record.work_mode))]);addOptions(fields.status,[...new Set(state.records.map(effectiveStatus))]);const fresh=state.records.filter(record=>effectiveStatus(record)==='Active').length,review=state.records.filter(record=>statusClass(record)==='review').length,closed=state.records.filter(record=>statusClass(record)==='closed').length;$('#catalogHealth').replaceChildren(el('strong',{text:String(state.records.length)}),el('span',{text:`records · ${fresh} current · ${review} need review · ${closed} closed`}));if(review){const notice=$('#freshnessNotice');notice.hidden=false;notice.textContent=`${review} listings are awaiting re-verification. Their source links remain available, but confirm availability with the employer before applying.`}applyFilters()}catch(error){$('#resultSummary').textContent='The catalog could not be loaded.';$('#results').replaceChildren(el('div',{className:'empty',text:'Please try again later.'}));$('#catalogHealth').replaceChildren(el('span',{text:'Catalog unavailable'}));console.error(error)}}
Object.values(fields).forEach(control=>control.addEventListener(control===fields.query?'input':'change',applyFilters));$('#clearFilters').addEventListener('click',()=>{$('#filters').reset();applyFilters();fields.query.focus()});loadCatalog();
