(function(){
  const fields={
    'Business & Management':['Business Analysis','Consulting & Strategy','Entrepreneurship','Human Resources','Operations Management','Product Management','Project & Program Management'],
    'Accounting & Finance':['Accounting','Audit & Assurance','Banking','Corporate Finance','Financial Analysis','Insurance & Risk','Investment Management','Tax','Valuation'],
    'Sales, Marketing & Customer Experience':['Advertising','Brand Management','Customer Success','Digital Marketing','Market Research','Public Relations','Sales & Business Development','Social Media Marketing'],
    'Technology & Computing':['Cloud & DevOps','Cybersecurity','Database Administration','IT Support','Network Engineering','Quality Assurance & Testing','Software Engineering','Systems Administration','Web Development'],
    'Data, AI & Mathematics':['Actuarial Science','Artificial Intelligence & Machine Learning','Business Intelligence','Data Analysis','Data Engineering','Data Science','Mathematics Research','Statistics'],
    'Engineering':['Aerospace Engineering','Biomedical Engineering','Chemical Engineering','Civil Engineering','Electrical Engineering','Environmental Engineering','Industrial Engineering','Manufacturing Engineering','Materials Engineering','Mechanical Engineering','Robotics & Automation'],
    'Physical Sciences':['Astronomy & Space Science','Chemistry Research','Earth & Geoscience','Environmental Testing','Forensic Science','Laboratory Technician','Materials Science','Meteorology','Physics Research'],
    'Life Sciences & Biotechnology':['Bioinformatics','Biology Research','Biotechnology','Ecology & Conservation','Genetics & Genomics','Microbiology','Neuroscience','Pharmaceutical Research','Wildlife Biology'],
    'Healthcare & Clinical':['Clinical Research','Dental Care','Health Administration','Medical Assistant','Nursing','Nutrition & Dietetics','Occupational Therapy','Pharmacy','Physical Therapy','Physician Support','Radiology & Imaging'],
    'Public Health':['Community Health','Epidemiology','Global Health','Health Education','Health Informatics','Health Policy','Occupational Health','Public Health Research'],
    'Education':['Academic Advising','Curriculum & Instruction','Early Childhood Education','Educational Technology','K-12 Teaching','Library & Information Science','Special Education','Student Affairs','Teaching Assistant & Tutoring'],
    'Social & Behavioral Sciences':['Anthropology','Behavioral Research','Economics Research','Human Services','Political Science Research','Psychology','Social Work','Sociology Research','User Research'],
    'Government & Public Policy':['Campaigns & Elections','Diplomacy & International Affairs','Emergency Management','Government Administration','Intelligence Analysis','Legislative Affairs','Policy Analysis','Public Administration','Urban & Regional Planning'],
    'Law, Compliance & Public Safety':['Compliance','Corporate Legal','Criminal Justice','Legal Assistant & Paralegal','Privacy & Data Protection','Public Safety','Regulatory Affairs','Security & Investigations'],
    'Arts, Design & Creative':['Animation','Architecture','Fashion Design','Fine Arts','Graphic Design','Industrial Design','Interior Design','Photography & Video','UX & UI Design'],
    'Media, Writing & Communications':['Broadcasting','Communications','Content Creation','Editing & Publishing','Journalism','Podcast & Audio','Screenwriting & Production','Technical Writing'],
    'Environment & Sustainability':['Climate & Energy','Environmental Policy','Environmental Science','Renewable Energy','Sustainability','Water Resources','Waste & Recycling'],
    'Agriculture, Food & Natural Resources':['Agribusiness','Animal Science','Food Science & Safety','Forestry','Horticulture','Natural Resources','Precision Agriculture','Veterinary Support'],
    'Skilled Trades & Technical Services':['Automotive Technology','Aviation Maintenance','Construction Trades','Electrical Trades','HVAC','Machining & CNC','Maintenance Technician','Welding'],
    'Hospitality, Tourism & Events':['Culinary Arts','Event Planning','Food & Beverage','Hotel Operations','Recreation Management','Tourism & Travel'],
    'Sports, Fitness & Recreation':['Athletic Administration','Coaching','Exercise Science','Fitness & Wellness','Sports Analytics','Sports Marketing','Sports Medicine'],
    'Nonprofit & Community Services':['Advocacy','Community Outreach','Fundraising & Development','Grant Writing','Nonprofit Operations','Volunteer Coordination','Youth Programs'],
    'Architecture, Construction & Real Estate':['Architecture','Construction Management','Facilities Management','Property Management','Real Estate','Surveying','Urban Design'],
    'Transportation, Logistics & Supply Chain':['Aviation Operations','Logistics','Procurement','Rail & Transit','Shipping & Maritime','Supply Chain','Transportation Planning','Warehouse Operations']
  };
  const majors=['Accounting','Actuarial Science','Aerospace Engineering','Agricultural Business','Agricultural Science','American Studies','Anthropology','Applied Mathematics','Architecture','Art History','Artificial Intelligence','Astronomy','Athletic Training','Biochemistry','Bioengineering','Bioinformatics','Biology','Biomedical Engineering','Biotechnology','Business Administration','Business Analytics','Chemical Engineering','Chemistry','Civil Engineering','Clinical Laboratory Science','Communications','Computer Engineering','Computer Information Systems','Computer Science','Construction Management','Criminal Justice','Cybersecurity','Data Analytics','Data Science','Dental Hygiene','Economics','Education','Electrical Engineering','Emergency Management','Engineering Management','English','Entrepreneurship','Environmental Engineering','Environmental Science','Exercise Science','Fashion Design','Film & Media Studies','Finance','Fine Arts','Food Science','Forensic Science','Forestry','Game Design','Geography','Geology','Graphic Design','Health Administration','Health Informatics','Health Sciences','History','Hospitality Management','Human Resources Management','Industrial Design','Industrial Engineering','Information Systems','Information Technology','International Business','International Relations','Journalism','Kinesiology','Legal Studies','Library Science','Linguistics','Management','Management Information Systems','Marine Biology','Marketing','Materials Science','Mathematics','Mechanical Engineering','Meteorology','Microbiology','Music','Neuroscience','Nonprofit Management','Nursing','Nutrition','Occupational Therapy','Operations Management','Paralegal Studies','Pharmacy','Philosophy','Photography','Physics','Political Science','Pre-Law','Pre-Medicine','Product Design','Psychology','Public Administration','Public Health','Public Policy','Public Relations','Radiologic Sciences','Real Estate','Robotics','Social Work','Sociology','Software Engineering','Special Education','Sports Management','Statistics','Supply Chain Management','Sustainability','Theatre','Tourism Management','Urban Planning','User Experience Design','Veterinary Science','Web Development','Wildlife Biology'];
  const minors=['Accounting','Advertising','African American Studies','Anthropology','Applied Statistics','Art History','Artificial Intelligence','Biology','Business','Business Analytics','Chemistry','Communication','Computer Science','Creative Writing','Criminal Justice','Cybersecurity','Data Science','Digital Media','Economics','Education','Engineering Leadership','Entrepreneurship','Environmental Studies','Finance','Foreign Language','Geographic Information Systems','Global Health','Graphic Design','Health Policy','History','Human Resources','Information Systems','International Business','International Relations','Journalism','Leadership Studies','Legal Studies','Management','Marketing','Mathematics','Media Studies','Nonprofit Leadership','Nutrition','Philosophy','Political Science','Project Management','Psychology','Public Health','Public Policy','Social Media','Sociology','Sports Management','Statistics','Supply Chain','Sustainability','Technical Writing','Urban Studies','User Experience'];
  const opportunityTypes=['Full-time job','Part-time job','Internship','Co-op','Entry-level job','Fellowship','Apprenticeship','Contract role','Temporary or seasonal job','Research position','On-campus job','Volunteer or service opportunity'];
  window.CAREER_TAXONOMY={fields,majors,minors,opportunityTypes};
})();
