import fs from 'node:fs/promises';
const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!key)throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required. Keep the service-role key in encrypted secrets.');
const source=JSON.parse(await fs.readFile(new URL('../opportunities.json',import.meta.url),'utf8'));
const clean=value=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const rows=source.filter(item=>!item.is_demo).map(item=>({company:item.company,role:item.role,location:item.location||[item.city,item.state].filter(Boolean).join(', '),role_family:item.role_family||item.category||'Other',industry:item.industry||'Other',field_key:item.field_key||null,role_key:item.role_key||null,opportunity_type:item.opportunity_type||'Internship',employment_type:item.employment_type||item.opportunity_type||'Internship',schedule_type:item.schedule_type||null,work_mode:item.work_mode||'Not listed',posting_url:item.posting_url||item.source_url||null,source_url:item.source_url||item.posting_url||null,source:item.source||'Verified employer source',tags:item.tags||[],deadline:item.deadline||null,term:item.term||null,city:item.city||null,state:item.state||null,listing_status:item.listing_status||'Active',details_eligibility:item.details_eligibility||null,description:item.description||item.details_eligibility||null,education_requirements:item.education_requirements||null,experience_level:item.experience_level||null,link_type:item.link_type||null,posting_verification:item.posting_verification||null,last_verified:item.last_verified||null,is_active:(item.listing_status||'Active')!=='Closed',is_demo:false,canonical_key:item.canonical_key||[item.company,item.role,item.term,item.city,item.state].map(clean).join('|'),updated_at:new Date().toISOString()}));
const response=await fetch(`${url}/rest/v1/opportunities_catalog?on_conflict=canonical_key`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(rows)});
if(!response.ok)throw new Error(`Catalog sync failed: ${response.status} ${await response.text()}`);
console.log(`Synced ${rows.length} verified opportunities.`);
